### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by RealVegOs** [truist/tru-tags#10]
[Fri Nov 18 14:02:28 2022] [php:error] [pid 20858] [client xx.xx.xx.xx] [host xxxxxxxxxxx] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /is/htdocs/xxxxxxxxxxx/www/xxxxxxxxxxx/xxxxxxxxxxx/plugins/tru_tags/tru_tags.php on line 469

My blog is nocked out. I even cannot log into the backend. Please fix this. Can I delete  the tru_tag table in the db or will this kill everything?

**Comment by wcz-txp** [comment]
You can find a fix [here](https://forum.textpattern.com/viewtopic.php?pid=327409#p327409).

**Comment by RealVegOs** [comment]
Are you serious? Really? People unknowingly installing tru_tags have to find out what's going on and whether there is a PHP 8 compatibility fix. Is is so hard for devs, to change some brackets in the source code? I like textpattern as it is very transparent for users knowing a bit XML or HTML, but this is a big point against recommending it to others.

**Comment by truist** [comment]
@RealVegOs I don't understand your comment? The day before yesterday, I published 3.10, that should fix this issue. https://www.rainskit.com/reference/537/tru_tags-releases
